**ДЗ_NUMPHY**

In [ ]:
import numpy as np
print("NumPy работает! Версия:", np.__version__)

**Counter**

In [ ]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

# Импортируем объект Counter из модуля collections
from collections import Counter
# Создаём пустой объект Counter
c = Counter()

c['red'] += 1
print(c)

c = Counter()
for car in cars:
    c[car] += 1

print(c)

c = Counter(cars)
print(c)
print(c['black'])
print(c['purple'])

print(sum(c.values()))
print(c.values())

In [ ]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow)
print(counter_spb)

print(counter_moscow + counter_spb)

"""Чтобы узнать разницу между объектами Counter, необходимо воспользоваться функцией subtract, которая меняет тот объект, к которому применяется."""

counter_moscow.subtract(counter_spb)
print(counter_moscow)

# Пересоздаём счётчики, потому что объект counter_moscow поменял свои значения
# после функции subtract.
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow - counter_spb)

"""Чтобы получить список всех элементов, которые содержатся в Counter, используется функция elements(). Она возвращает итератор, поэтому, чтобы напечатать все элементы, распакуем их с помощью *"""
print(*counter_moscow.elements())

print(list(counter_moscow))

print(dict(counter_moscow))

print(counter_moscow.most_common())

print(counter_moscow.most_common(2))

counter_moscow.clear()
print(counter_moscow)

In [ ]:
"""Упражнения"""

clients = [
    953421102, 123456789, 953421102, 987654321, 953421102,
    123456789, 555666777, 953421102, 987654321, 123456789,
    953421102, 555666777, 123456789, 953421102, 111222333,
    953421102, 987654321, 123456789, 953421102, 555666777,
    123456789, 953421102, 111222333, 987654321, 953421102,
    123456789, 555666777, 953421102, 123456789, 953421102
]

from collections import Counter
# Создаём пустой объект Counter
c = Counter()

Fr_client = Counter(clients)
print(Fr_client)
print(Fr_client.most_common(1)[0][0])
print(Fr_client.most_common(1)[0][1])

#Сколько уникальных номеров
print(list(Fr_client))

print(Fr_client[953421102])



**Defaultdict**

In [ ]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

groups = dict()
 
for student, group in students:
    # Проверяем, есть ли уже эта группа в словаре
    if group not in groups:
        # Если группы ещё нет в словаре, создаём для неё пустой список
        groups[group] = list()
    groups[group].append(student)
 
print(groups)


"""Теперь тот же код, который вызывал ошибку при работе с обычным словарём, сработает так, как ожидается:"""

from collections import defaultdict

groups = defaultdict(list)

for student, group in students:
    groups[group].append(student)
 
print(groups.keys())

print(groups[3])

print(groups[2021])

print(groups)


defaultdict_object = defaultdict()
 
print(type(dict_object))
# <class 'dict'>
print(type(defaultdict_object))
# <class 'collections.defaultdict'>

print(dict_object)
# {}
print(defaultdict_object)
# defaultdict(None, {})

In [ ]:
from collections import defaultdict, deque
from collections import Counter, OrderedDict

students = [
    ('Ivanov', 1), ('Smirnov', 4), ('Petrov', 3),
    ('Kuznetsova', 1), ('Nikitina', 2), ('Markov', 3),
    ('Pavlov', 2), ('Sidorov', 1)
]

#groups = defaultdict(group)
groups = defaultdict(list)



for name, group in students:
    
    groups[group].append(name)
    
print(groups)
print(groups.keys())
print(groups.items())

print(groups[1])
print((groups)[1][1])
print(*groups.values())

"""Задача _2"""
words = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple', 'kiwi']

from collections import Counter
# Создаём пустой объект Counter

c = Counter(words)
print(c.most_common(1))



**OrderedDict**

In [ ]:
# Напоминаем способ создания словаря через список кортежей
# (ключ, значение)
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
client_ages = dict(data)
print(client_ages)
# По результатам 3 повторов получились вот такие результаты:
# {'Maria': 20, 'Mark': 25, 'Ivan': 19, 'Andrey': 23}
# {'Ivan': 19, 'Andrey': 23, 'Mark': 25, 'Maria': 20}
# {'Andrey': 23, 'Mark': 25, 'Maria': 20, 'Ivan': 19}

from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)
# По результатам 3 повторов получились вот такие результаты:
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])

data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
# Сортируем по второму значению из кортежа, то есть по возрасту
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])

ordered_client_ages['Nikita'] = 18
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Nikita', 18)])

del ordered_client_ages['Andrey']
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18)])
ordered_client_ages['Andrey'] = 23
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18), ('Andrey', 23)])

import sys
print(sys.version)
# 3.4.3 (default, Nov 12 2018, 22:25:49)
# [GCC 4.8.4]

In [ ]:
items = [
    ('Milk', 'dairy'), ('Bread', 'bakery'), ('Cheese', 'dairy'),
    ('Cola', 'drinks'), ('Yoghurt', 'dairy'), ('Beer', 'drinks'),
    ('Croissant', 'bakery'), ('Juice', 'drinks')
]



**Deque**

In [ ]:
from collections import deque
dq = deque()
print(dq)
# deque([])

clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])

print(clients[2])
# Smirnov

first_client = clients.popleft()
second_client = clients.popleft()
 
print("First client:", first_client)
print("Second client:", second_client)
print(clients)
# First client: Ivanov
# Second client: Petrov
# deque(['Smirnov', 'Tikhonova'])

clients.appendleft('Vip-client')
 
print(clients)
# deque(['Vip-client', 'Smirnov', 'Tikhonova'])

tired_client = clients.pop()
print(tired_client, "left the queue")
print(clients)
# Tikhonova left the queue
# deque(['Vip-client', 'Smirnov'])

clients = deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
del clients[2]
print(clients)
# deque(['Ivanov', 'Petrov', 'Tikhonova'])

"""Также в очередь возможно добавить сразу несколько элементов из итерируемого объекта в дек.
Для этого используют функции extend (добавить в конец дека) и extendleft (добавить в начало дека)."""

# В скобках передаём список при создании deque,
# чтобы сразу добавить все его элементы в очередь
shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)
# deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])

shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)
# deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])

"""Очередь с ограниченной максимальной длиной"""

limited = deque(maxlen=3)
print(limited)
# deque([], maxlen=3)
 
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)
# deque([5, 6, 7], maxlen=3)

limited.extend([1,2,3])
print(limited)
# deque([1, 2, 3], maxlen=3)


"""Также заметьте, что в очереди с ограниченной длиной сохраняются только последние элементы, а первые исчезают из памяти:"""
print(limited.append(8))
# None
print(limited)
# deque([2, 3, 8], maxlen=3)

"""Посчитаем динамику средней температуры с усреднением за каждые последние 7 дней для каждого рассматриваемого дня. 
Для этого воспользуемся очередью с параметром maxlen=7:"""

temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

days = deque(maxlen=7)
 
for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")
# Результат:
# 20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97;
# 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4;
# 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67;

"""reverse позволяет поменять порядок элементов в очереди на обратный:"""
dq = deque([1,2,3,4,5])
print(dq)
# deque([1, 2, 3, 4, 5])
 
dq.reverse()
print(dq)
# deque([5, 4, 3, 2, 1])

"""rotate переносит  заданных элементов из конца очереди в начало:"""

dq = deque([1,2,3,4,5])
print(dq)
# deque([1, 2, 3, 4, 5])
 
dq.rotate(2)
print(dq)
# deque([4, 5, 1, 2, 3])

"""Элементы можно переносить и из начала в конец:"""

print(dq)
# deque([1, 2, 3, 4, 5])
 
# Отрицательное значение аргумента переносит
# n элементов из начала в конец
dq.rotate(-2)
print(dq)
# deque([3, 4, 5, 1, 2])

"""Функция index позволяет найти первый индекс искомого элемента, а count позволяет подсчитать,
сколько раз элемент встретился в очереди (функции аналогичны одноимённым функциям для списков):"""

dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
# 2
print(dq.count(4))
# 6

"""Обратите внимание, что при попытке узнать индекс несуществующего элемента возникнет ValueError:"""

dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.index(25))
# ValueError: 25 is not in deque

"""А вот посчитать несуществующий элемент можно (получится просто 0):"""
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.count(25))
# 0
"""Наконец, функция clear позволяет очистить очередь:"""

dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq)
# deque([1, 2, 4, 2, 3, 1, 5, 4, 4, 4, 4, 4, 3])
dq.clear()
print(dq)
# deque([])

In [ ]:
from collections import deque
dq = deque()
print(dq)

users = [
    101, 102, 101, 103, 104, 102, 105, 101, 106, 107,
    102, 101, 103, 108, 101, 104, 102, 105, 101, 106,
    107, 101, 102, 103, 104, 101, 105, 106, 101, 107
]

"""Добавить элемент в конец очереди
Извлечь элемент из начала очереди
Добавить несколько элементов в конец очереди
Добавить несколько элементов в начало очереди
Переместить несколько элементов из конца в начало (или наоборот)
Перевернуть очередь"""

clients = deque(users) 


clients.popleft()
clients.append(1)
clients.extend([3, 4, 5])
clients.appendleft([1, 2, 3])
clients.reverse()
clients.rotate(-5)


print(clients)
# print(no_left)
# print(few_new)
# print(few_new_1)
# print(few_new_left)
# print(new_rev)


In [ ]:
"""
Задача 
В импортируемых в тренировочном редакторе кода переменных center, south и north хранятся списки из перечней купленных позиций в трёх торговых точках, 
расположенных в разных районах города.
Вначале избавьтесь от излишней вложенности: в каждой переменной (center, south, north) 
должен храниться объединённый список купленных товаров без разбиения по чекам.

Пример:[['Milk', 'Bread'], ['Meat']] -> ['Milk', 'Bread', 'Meat']

"""

center = [
    ['Milk', 'Bread'], ['Meat'], ['Milk', 'Cola'],
    ['Bread', 'Yoghurt'], ['Milk', 'Beer'], ['Cola'],
    ['Milk', 'Bread', 'Meat'], ['Yoghurt'], ['Milk'],
    ['Bread', 'Cola'], ['Milk', 'Yoghurt'], ['Beer']
]

south = [
    ['Bread'], ['Milk', 'Cola'], ['Meat', 'Bread'],
    ['Yoghurt', 'Milk'], ['Cola'], ['Bread', 'Beer'],
    ['Milk'], ['Yoghurt', 'Cola'], ['Bread', 'Milk'],
    ['Beer', 'Milk'], ['Cola', 'Yoghurt']
]

north = [
    ['Milk', 'Bread', 'Cola'], ['Meat'], ['Beer'],
    ['Milk', 'Yoghurt'], ['Bread'], ['Cola', 'Milk'],
    ['Yoghurt', 'Beer'], ['Milk', 'Bread'], ['Cola'],
    ['Milk'], ['Bread', 'Yoghurt', 'Beer'], ['Cola'],
    ['Milk', 'Bread']
]

center_flat = []
for chek in center:
    for tovar in chek:
        center_flat.append(tovar)
        
south_flat = []
for chek in south:
    for tovar in chek:
        south_flat.append(tovar)
        
north_flat = []
for chek in north:
    for tovar in chek:
        north_flat.append(tovar)
        
        
        
#ВАЖНО!!!! СЧЕТЧИК ДЛЯ РАСПВАКОВКИ - запись по сути аналогичная
center_flat_1=[tovar for chek in center for tovar in chek]

        
lengths = {'center': len(center_flat), 'south': len(south_flat), 'north': len(north_flat)}        

best_shop = max(lengths, key = lengths.get)

print(*center_flat)
print(*south_flat)
print(*north_flat)
print(best_shop)

"""Теперь получи объекты-счётчики (Counter) из каждого полученного в предыдущем задании списка покупок и сохрани их в 
отдельные переменные (они пригодятся для следующих задач).

Сколько раз покупали самый редкий товар в магазине north? Запиши ответ в числовой форме."""

from collections import Counter
# Создаём пустой объект Counter


c_1 = Counter(center_flat)
c_2 = Counter(south_flat)
c_3 = Counter(north_flat)
print(c_1, c_2, c_3)

print(min(c_3.values()))

rarest = (min(c_3.values()))
for tovar, count in c_3.items():
    if count == rarest:
        print(tovar)
        
    
        
print(center_flat_1)


for tovar in ['Beer', 'Cola', 'Bread', 'Yoghurt']:
    if c_1[tovar]> c_3[tovar]:
        print(tovar)
#ount_north = 

"""Определи суммарное число продаж каждого товара во всех магазинах, сложив все объекты-счётчики. 
Сколько раз был куплен второй по популярности товар? Запиши ответ числом.
"""

general = c_1 + c_2 + c_3

print(general)
print(general.most_common()[1][1])


**NUMPY**

In [ ]:
import numpy as np

a = np.int64()
print(a)
# Можно применить к самому
# названию типа данных

# iinfo(min=-128, max=127, dtype=int8)

# Можно применить к существующему
# конкретному объекту
np.iinfo(a)
# iinfo(min=-128, max=127, dtype=int8)

# b = np.uint1(-456)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)

arr, step = np.linspace(-6, 21, 60, retstep=True)
print(arr)
print(round(step, 2))


arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(arr)
print(round(step, 2))

In [ ]:
"""Вектора"""

import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 4.0, 6.0])
c = np.array([1.0, -2.0, 3.0])

print("a =", a)
print("b =", b)
print("c =", c)

"""Перпедикулярные сколярное произв равно 0"""
"""Один из них: сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов"""
"""Длинна векторов"""
length_a = np.linalg.norm(a)
length_b = np.linalg.norm(b)
length_c = np.linalg.norm(c)

a_b = a + b
a_c = a + c
b_c = b + c

length_a_b = np.linalg.norm(a_b)
length_a_c = np.linalg.norm(a_c)
length_b_c = np.linalg.norm(b_c)

length_a + length_b == length_a_b
length_a + length_c == length_a_c
length_b + length_c == length_b_c

distance_a_b = np.linalg.norm(a-b)
distance_a_c = np.linalg.norm(a-c)
distance_b_c = np.linalg.norm(b-c)

print(distance_a_b)
print(distance_b_c)
print(distance_a_c)

scal_a_b = np.dot(a, b)
scal_a_c = np.dot(a, c)
scal_b_c = np.dot(b, c)

print(scal_a_b)
print(scal_b_c)
print(scal_a_c)



In [ ]:
import numpy as np

mystery2 = np.array([12.5, 7.3, 18.9, 3.2, 15.6, 9.8, 21.4, 6.7, 14.2, 11.1])
print(mystery2)

print(mystery2.min())
print(np.mean(mystery2))

print(mystery2.mean())

print(mystery2.median())

print(np.median(mystery2))

print(mystery2.std())

In [ ]:
"""Решение"""
import numpy as np


def get_chess(a):
    board = np.zeros((a, a))
    board[0::2, 1::2] = 1 #в оригингале было  board[::2, 1::2]- проверить одно лит эт о и то же или нет!!!!
    board[1::2, 0::2] = 1
    
    return board

print(get_chess(5))


In [ ]:
import numpy as np

# def shuffle_seed(array):
#     seed = np.random.randit(0, 2**32)
#     np.random.seed(seed)
#     shuffled = np.random.permutation(array)
    
    
#     return shuffled, seed
 
 
 


def shuffle_seed(array):
    # Генерируем случайный seed в диапазоне [0, 2**32 - 1]
    seed = np.random.randint(0, 2**32)
    
    # Перемешиваем массив с этим seed
    np.random.seed(seed)
    shuffled = np.random.permutation(array)
    
    return shuffled, seed
 
#     array = [1, 2, 3, 4, 5]
#     print(shuffle_seed(array))   
 

# array = [1, 2, 3, 4, 5]

shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)

shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)

"""np.random.randint(0, 2**32)
random.randint(0, 2**32)
np.random.randint(0, 2**32 - 1)
np.random.random(2**32 - 1)"""

In [274]:
import numpy as np
from itertools import combinations

def mean_dist(*vectors):
    distances = [np.linalg.norm(v1-v2) for v1, v2 in combinations(vectors, 2)]
    
    return np.mean(distances)

print(mean_dist(vec1, vec2, vec3))

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])

mean_dist(vec1, vec2, vec3)
# 6.928203230275509



6.92820323027551


np.float64(6.92820323027551)

In [288]:
import numpy as np
from itertools import combinations

vec1 = np.array([1, 2])
vec2 = np.array([-2, -4])
vec3 = np.array([3, 1])

def any_normal(*vectors):
    for v1, v2 in combinations(vectors, 2):
        if np.sum(v1 + v2) == 0:
            return True
    return False

print(any_normal(vec1, vec2, vec3))



False


In [ ]:
import numpy as np

def get_scores(num):
    return np.random.randint(0, 101, (num, 4, 4)) #  ЧУМА!

print(get_scores(4))

def get_unique_scores(num):
    tables = []
    for _ in range(num):
        unique_vals = np.random.choice(101, size=(4, 4), replace=False)# ЧУМА - сразу задали размеры таблицы size=(4, 4)
        tables.append(unique_vals)
    return np.array(tables)
    #     unique_vals = np.random.choice(101, 16, replace = False)
    #     table = unique_vals.reshape(4, 4)
    #     tables.append(table)
    # return np.array(tables)



print(get_unique_scores(5))

[[[95 25 86 12]
  [79  5 78 31]
  [43 55  9 56]
  [80 33 98 62]]

 [[29 63 85 50]
  [39 54 37 62]
  [20 94 34 48]
  [76 44 10 67]]

 [[94 38  1 99]
  [44 91 92 53]
  [99 32 25 53]
  [39 81 49 98]]

 [[33 61 99 26]
  [50 72  0 86]
  [39 22 97 14]
  [60 95 25 18]]]
[[[47 71 70  6]
  [88 29 64 28]
  [22 95 84 11]
  [89 58 96 79]]

 [[65 97  2 72]
  [ 4 80 10 42]
  [43 13 38  5]
  [23 67 55 94]]

 [[39 32 23 94]
  [ 4  5  9 87]
  [61 67 10  0]
  [64  2 69 41]]

 [[88  8 97 39]
  [ 9 65 84  7]
  [92 41  0 85]
  [69 26 78 99]]

 [[87 33 23 39]
  [58 32 86 57]
  [99 76 11 80]
  [65 75 28 14]]]
